// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX_fLqLImldlWKGOM8mrR2CMonV3eQaao',
    appId: '1:904869524122:web:0493ec16b6db44e2822523',
    messagingSenderId: '904869524122',
    projectId: 'twitch-clone-46a19',
    authDomain: 'twitch-clone-46a19.firebaseapp.com',
    storageBucket: 'twitch-clone-46a19.appspot.com',
    measurementId: 'G-0K880P1BPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE9vKEOoA0hBa4HWYlIHCXrU158R7PeVU',
    appId: '1:904869524122:android:3863bccdb25c0bf3822523',
    messagingSenderId: '904869524122',
    projectId: 'twitch-clone-46a19',
    storageBucket: 'twitch-clone-46a19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKKbYs2s6oVy0yoPkC9QGm-_hSsL0LLvM',
    appId: '1:904869524122:ios:c2815437955f60e0822523',
    messagingSenderId: '904869524122',
    projectId: 'twitch-clone-46a19',
    storageBucket: 'twitch-clone-46a19.appspot.com',
    iosBundleId: 'com.example.twitchClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKKbYs2s6oVy0yoPkC9QGm-_hSsL0LLvM',
    appId: '1:904869524122:ios:0881fb50902317de822523',
    messagingSenderId: '904869524122',
    projectId: 'twitch-clone-46a19',
    storageBucket: 'twitch-clone-46a19.appspot.com',
    iosBundleId: 'com.example.twitchClone.RunnerTests',
  );
}
